Update some translation of Chinese(Simplified)
buresdv/Cork pull request #393
Opened 2024-08-31 15:41 UTC by Lucas04-nhr

FIx some typos and add some new items.

2024-08-31 16:49 UTC, Jerry23011 commented
Thank you, just a few details that we want to pay attention to. Please see me reviews. Thank you

2024-08-31 16:59 UTC, Jerry23011 requested changes

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "这个 Cask 已在应用程序文件夹中存在 请卸载它然后尝试重试安装"
Please add a comma: `这个 Cask 已在应用程序文件夹中存在 ，请卸载它然后尝试重试安装`

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "调试：激活演示模式"
Please use 半角 for this case `:` sometimes 全角 punctuations case UI glitches

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "调试：正在激活许可证"
半角 for this one as well

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "调试：重置许可状态"
半角 for this one as well

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "Homebrew命令中未正确设置HOME变量"
For this one, we want to leave a space between English and Chinese characters. `Homebrew 命令中未正确设置 HOME 变量`

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "未完成获取过时软件包：%@"
we are not using “过时软件包” to refer to outdated packages, it sound a bit "machine-like". Please refer to the rest of the translations for outdated packages.

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "并未安装软件包%@的任何版本"
Please leave a blank between %@ and the Chinese characters as the name of the packages are usually in English

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "%@不是一个软件包路径"
Please leave a blank between %@ and the Chinese characters for this one as well

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "无法加载软件包%1$@（%2$@）：%3$@"
Please leave a blank between %@ and the Chinese characters for this one as well

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "无法加载软件包：%@"
Please use 半角 for the punctuation here

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "所提供的路径指向Cask文件夹本身，并非指向软件包。 你的Homebrew程序损坏，这并非是Cork的问题"
Please leave space between the English and Chinese characters

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "所提供的路径指向Formulae文件夹本身，并非指向软件包。 你的Homebrew程序损坏，这并非是Cork的问题"
Please leave space between the English and Chinese characters

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "无法从所提供的软件包跟踪器UUID中找到任何软件包"
Please leave space between the English and Chinese characters

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "正则表达式不匹配任何结果"
`正则表达式没有任何匹配结果`

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "无法移除tap%1$@(输出：%2$@)"
Please capitalize the T in tap and leave spaces between $@ and the punctuation, the English letters and the Chinese characters. Also please use 半角 Chinese punctuations.

2024-08-31 16:59 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "无法解码热门Cask"
Please leave space between Chinese characters and English letters

2024-09-01 01:30 UTC, Lucas04-nhr commented on Cork/Localizable.xcstrings
> +            "value" : "未完成获取过时软件包：%@"
Change the translate to "更早的软件包"

2024-09-01 01:40 UTC, Lucas04-nhr reviewed
Thanks for giving me instructions about some localization.

2024-09-01 01:40 UTC, Lucas04-nhr commented on Tuist/Package.resolved
This package is maybe automatically added by tuist or XCode, I didn't mean to do this.

2024-09-01 03:06 UTC, Jerry23011 requested changes

2024-09-01 03:06 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "无法确定brewfile导出过程是从何处启动"
Please leave a space between English and Chinese characters

2024-09-01 03:06 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "Homebrew 服务器返回错误%lld"
Homebrew 服务器返回错误 %lld

2024-09-01 03:06 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "无法从 Homebrew 中解码 JSON 响应 %@"
Please remember to add the line break
`无法从 Homebrew 中解码 JSON 响应:\n%@`

PS. No need to add space between colon and line break

2024-09-01 03:06 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "所提供的路径指向 Cask 文件夹本身，并非指向软件包。 你的 Homebrew 程序损坏，这并非是Cork的问题"
Please leave space between English and Chinese characters

2024-09-01 03:06 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "所提供的路径指向 Formulae 文件夹本身，并非指向软件包。 你的 Homebrew 程序损坏，这并非是Cork的问题"
Please leave space between English and Chinese characters

2024-09-01 03:06 UTC, Jerry23011 commented on Cork/Localizable.xcstrings
> +            "value" : "所提供的路径指向 Formulae 文件夹本身，并非指向软件包。 你的 Homebrew 程序损坏，这并非是Cork的问题"
We just need to keep the singular form of Formula/Cask/Tap in Chinese translations since we don't have the concept of plurals anyway

2024-09-01 03:37 UTC, Jerry23011 commented
Thank you so much for all the work. I'm good with the translations. Just need to confirm the newly added package @buresdv

2024-09-01 03:37 UTC, Jerry23011 approved these changes

2024-09-01 09:15 UTC, buresdv commented
@Jerry23011 Thank you so much for reviewing the PR! I can confirm that the package is correct. I'll merge this

2024-09-01 09:15 UTC, merged

2024-09-01 09:21 UTC, Jerry23011 commented
> @Jerry23011 Thank you so much for reviewing the PR! I can confirm that the package is correct. I'll merge this

Thank you!